
Concept.create([
	{body: "Talking about politics"},
	{body: "Raisins"},
	{body: "Going to a party"},
	{body: "Talking on the phone"},
	{body: "Facebook"},
	{body: "Running"},
	{body: "Sour Patch Kids"},
	{body: "Classical music"},
	{body: "Cleaning house"},
	{body: "Children"},
	{body: "HGTV"},
	{body: "Michelle Obama"},
	{body: "Amazon.com"},
	{body: "Jewelry"},
	{body: "Driving at night"},
	{body: "Cooking"},
	{body: "Hillary Clinton"},
	{body: "Microsoft"},
	{body: "Winter"},	
	{body: "Abstract art"},
	{body: "Going to the movies"},
	{body: "Football"},
	{body: "Getting blood taken"},
	{body: "Gardening"},
	{body: "McDonalds"},
	{body: "Traveling to foreign countries"},
	{body: "Musicals"},
	{body: "Chipotle"},
	{body: "Going to the dentist"},
	{body: "Tennis"},
	{body: "Hiking"},
	{body: "Rainy days"},
	{body: "Recycling"},
	{body: "Country music"},
	{body: "Tom Hanks"},
	{body: "Flying on airplanes"},
	{body: "Ice Skating"},
	{body: "Osama bin Laden"},
	{body: "Boardgames"},
	{body: "Harry Potter"},
	{body: "Skateboarding"},
	{body: "Katie Couric"},
	{body: "Biking"},
	{body: "Coffee"}
	])